@baseAddress = https://localhost:7185

POST /api/PeopleAPI HTTP/1.1
Host: @baseAddress
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="FirstName"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="SecondName"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="ThirdName"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="LastName"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Gender"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="DateOfBirth"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="NationalNumber"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="PhoneNumber"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="CountryID"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Address"


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="ImageFile"

@filename
------WebKitFormBoundary7MA4YWxkTrZu0gW--
