// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using  SMS.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SMS.Infrastructure.Configurations;

public partial class ClassConfiguration : IEntityTypeConfiguration<Class>
{
    public void Configure(EntityTypeBuilder<Class> entity)
    {
        entity.HasIndex(e => new { e.GradeLevelID, e.SectionName }, "UC_GradeLevel_Section").IsUnique();

        entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Classes_IsActive");
        entity.Property(e => e.SectionName).HasMaxLength(5);

        entity.HasOne(d => d.GradeLevel).WithMany(p => p.Classes)
            .HasForeignKey(d => d.GradeLevelID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Classes_GradeLevel");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Class> modelBuilder);
}
