// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using  SMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SMS.DataAccess.Configurations;

public partial class ClassSubjectConfiguration : IEntityTypeConfiguration<ClassSubject>
{
    public void Configure(EntityTypeBuilder<ClassSubject> entity)
    {
        entity.HasIndex(e => new { e.GradeLevelID, e.SubjectID }, "UC_GradeLevel_Subject").IsUnique();

        entity.HasOne(d => d.GradeLevel).WithMany(p => p.ClassSubjects)
            .HasForeignKey(d => d.GradeLevelID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ClassSubjects_GradeLevel");

        entity.HasOne(d => d.Subject).WithMany(p => p.ClassSubjects)
            .HasForeignKey(d => d.SubjectID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_ClassSubjects_Subjects");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<ClassSubject> modelBuilder);
}
