// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using  SMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SMS.DataAccess.Configurations;

public partial class EnrollmentConfiguration : IEntityTypeConfiguration<Enrollment>
{
    public void Configure(EntityTypeBuilder<Enrollment> entity)
    {
        entity.Property(e => e.AcademicYear).HasMaxLength(10);
        entity.Property(e => e.EnrollmentDate).HasDefaultValueSql("(getdate())");
        entity.Property(e => e.Notes).HasMaxLength(500);
        entity.Property(e => e.Status).HasComment("1= Active, 2= vacation, 3= Promoted, 4= Failed, 5= Dropped, 6= Transferred");

        entity.HasOne(d => d.Class).WithMany(p => p.Enrollments)
            .HasForeignKey(d => d.ClassID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Enrollments_Classes");

        entity.HasOne(d => d.Student).WithMany(p => p.Enrollments)
            .HasForeignKey(d => d.StudentID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Enrollments_Students");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Enrollment> modelBuilder);
}
