// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using  SMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SMS.DataAccess.Configurations;

public partial class GradeLevelConfiguration : IEntityTypeConfiguration<GradeLevel>
{
    public void Configure(EntityTypeBuilder<GradeLevel> entity)
    {
        entity.ToTable("GradeLevel");

        entity.Property(e => e.GradeLevelName)
            .HasMaxLength(10)
            .HasColumnName("GradeLevel");
        entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_GradeLevel_IsActive");

        entity.HasOne(d => d.Stage).WithMany(p => p.GradeLevels)
            .HasForeignKey(d => d.StageID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_GradeLevel_Stages");

        entity.HasOne(d => d.Track).WithMany(p => p.GradeLevels)
            .HasForeignKey(d => d.TrackID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_GradeLevel_Tracks");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<GradeLevel> modelBuilder);
}
