// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using  SMS.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SMS.Infrastructure.Configurations;

public partial class Guardians_StudentConfiguration : IEntityTypeConfiguration<Guardians_Student>
{
    public void Configure(EntityTypeBuilder<Guardians_Student> entity)
    {
        entity.HasKey(e => new { e.GuardianID, e.StudentID });

        entity.Property(e => e.RelationshipType).HasMaxLength(50);

        entity.HasOne(d => d.Guardian).WithMany(p => p.Guardians_Students)
            .HasForeignKey(d => d.GuardianID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Guardians_Students_Guardians");

        entity.HasOne(d => d.Student).WithMany(p => p.Guardians_Students)
            .HasForeignKey(d => d.StudentID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Guardians_Students_Students");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Guardians_Student> modelBuilder);
}
