// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using  SMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SMS.DataAccess.Configurations;

public partial class GuardianConfiguration : IEntityTypeConfiguration<Guardian>
{
    public void Configure(EntityTypeBuilder<Guardian> entity)
    {
        entity.Property(e => e.GuardianID).ValueGeneratedNever();
        entity.Property(e => e.JobTitle).HasMaxLength(50);

        entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Guardians)
            .HasForeignKey(d => d.CreatedByUserID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Guardians_CreatedByUserID");

        entity.HasOne(d => d.Person).WithOne(p => p.Guardian)
            .HasForeignKey<Guardian>(d => d.GuardianID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Guardians_People");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Guardian> modelBuilder);
}
