// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using  SMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SMS.DataAccess.Configurations;

public partial class PersonConfiguration : IEntityTypeConfiguration<Person>
{
    public void Configure(EntityTypeBuilder<Person> entity)
    {
        entity.HasIndex(e => e.CountryID, "IX_People_CountryID");

        entity.HasIndex(e => new { e.FirstName, e.SecondName, e.ThirdName }, "IX_People_FullName");

        entity.HasIndex(e => e.NationalNumber, "IX_People_NationalNumber").IsUnique();

        entity.HasIndex(e => e.PhoneNumber, "IX_People_PhoneNumber").IsUnique();

        entity.Property(e => e.Address).HasMaxLength(200);
        entity.Property(e => e.FirstName).HasMaxLength(20);
        entity.Property(e => e.Gender)
            .HasMaxLength(1)
            .IsUnicode(false)
            .IsFixedLength();
        entity.Property(e => e.ImagePath).HasMaxLength(350);
        entity.Property(e => e.LastName).HasMaxLength(20);
        entity.Property(e => e.NationalNumber).HasMaxLength(15);
        entity.Property(e => e.PhoneNumber)
            .HasMaxLength(12)
            .IsUnicode(false);
        entity.Property(e => e.SecondName).HasMaxLength(20);
        entity.Property(e => e.ThirdName).HasMaxLength(20);

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Person> modelBuilder);
}
