// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using  SMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SMS.DataAccess.Configurations;

public partial class StudentConfiguration : IEntityTypeConfiguration<Student>
{
    public void Configure(EntityTypeBuilder<Student> entity)
    {
        entity.Property(e => e.StudentID).ValueGeneratedNever();
        entity.Property(e => e.StudentStatus).HasComment(" { Active = 1, vacation = 2, Graduated = 3, Transferred = 4, DroppedOut = 5 }");

        entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Students)
            .HasForeignKey(d => d.CreatedByUserID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Students_CreatedByUserID");

        entity.HasOne(d => d.CurrentClass).WithMany(p => p.Students)
            .HasForeignKey(d => d.CurrentClassID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Students_CurrentClassID");

        entity.HasOne(d => d.Person).WithOne(p => p.Student)
            .HasForeignKey<Student>(d => d.StudentID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Students_People");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Student> modelBuilder);
}
