// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using  SMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SMS.DataAccess.Configurations;

public partial class StudentGradeConfiguration : IEntityTypeConfiguration<StudentGrade>
{
    public void Configure(EntityTypeBuilder<StudentGrade> entity)
    {
        entity.HasKey(e => e.GradeID);

        entity.HasIndex(e => new { e.EnrollmentID, e.SubjectID, e.ExamTypeID }, "UC_Enrollment_Subject_ExamType").IsUnique();

        entity.Property(e => e.Mark).HasColumnType("decimal(5, 2)");
        entity.Property(e => e.Notes).HasMaxLength(200);

        entity.HasOne(d => d.Enrollment).WithMany(p => p.StudentGrades)
            .HasForeignKey(d => d.EnrollmentID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_StudentGrades_Enrollments");

        entity.HasOne(d => d.ExamType).WithMany(p => p.StudentGrades)
            .HasForeignKey(d => d.ExamTypeID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_StudentGrades_ExamTypes");

        entity.HasOne(d => d.Subject).WithMany(p => p.StudentGrades)
            .HasForeignKey(d => d.SubjectID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_StudentGrades_Subjects");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<StudentGrade> modelBuilder);
}
