// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using  SMS.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SMS.Infrastructure.Configurations;

public partial class TeacherConfiguration : IEntityTypeConfiguration<Teacher>
{
    public void Configure(EntityTypeBuilder<Teacher> entity)
    {
        entity.Property(e => e.TeacherID)
            .ValueGeneratedNever()
            .HasComment("");
        entity.Property(e => e.Qualification).HasMaxLength(50);
        entity.Property(e => e.TeacherStatus).HasComment("Active = 1, vacation = 2,  Transferred = 3,  Retired = 4  ");

        entity.HasOne(d => d.CreatedByUser).WithMany(p => p.Teachers)
            .HasForeignKey(d => d.CreatedByUserID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Teachers_CreatedByUserID");

        entity.HasOne(d => d.Person).WithOne(p => p.Teacher)
            .HasForeignKey<Teacher>(d => d.TeacherID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Teachers_People");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Teacher> modelBuilder);
}
