// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using  SMS.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace SMS.Infrastructure.Configurations;

public partial class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> entity)
    {
        entity.HasIndex(e => e.Username, "UC_Username").IsUnique();

        entity.HasIndex(e => e.PersonID, "UNIQUE_PersonID_Users").IsUnique();

        entity.Property(e => e.IsActive).HasDefaultValue(true, "DF_Users_IsActive");
        entity.Property(e => e.PasswordHash)
            .HasMaxLength(64)
            .IsUnicode(false);
        entity.Property(e => e.PasswordSalt).HasMaxLength(32);
        entity.Property(e => e.Username).HasMaxLength(20);

        entity.HasOne(d => d.CreatedByUser).WithMany(p => p.InverseCreatedByUser)
            .HasForeignKey(d => d.CreatedByUserID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Users_CreatedByUserID");

        entity.HasOne(d => d.Person).WithOne(p => p.User)
            .HasForeignKey<User>(d => d.PersonID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Users_People");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<User> modelBuilder);
}
