// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using SMS.Domain.Entities;
using System.Collections.Generic;

namespace  SMS.Domain.Entities;

public partial class ClassSubject
{
    public int ClassSubjectID { get; set; }

    public int GradeLevelID { get; set; }

    public int SubjectID { get; set; }

    public virtual GradeLevel GradeLevel { get; set; } = null!;

    public virtual Subject Subject { get; set; } = null!;
}
