// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using SMS.Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SMS.Core.Entities;

public partial class Class
{
    [Required(ErrorMessage = "Class ID is required.")]
    [Range(1, int.MaxValue, ErrorMessage = "Invalid Class ID.")]
    public int ClassID { get; set; }

    [Required(ErrorMessage = "Grade level is required.")]
    [Range(1, int.MaxValue, ErrorMessage = "Invalid Grade Level ID.")]
    public int GradeLevelID { get; set; }

    [Required(ErrorMessage = "Section name is required.")]
    [StringLength(5, ErrorMessage = "Section name cannot exceed 5 characters.")]
    public string SectionName { get; set; } = null!;

    public bool IsActive { get; set; }

    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();

    public virtual GradeLevel GradeLevel { get; set; } = null!;

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}
