// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace  SMS.Core.Entities;

public partial class ExamType
{
    public byte ExamTypeID { get; set; }

    public string ExamTypeName { get; set; } = null!;

    public virtual ICollection<StudentGrade> StudentGrades { get; set; } = new List<StudentGrade>();
}
