// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace  SMS.Core.Entities;

public partial class Guardians_Student
{
    [Required(ErrorMessage = "Guardian ID is required.")]
    [Range(1, int.MaxValue, ErrorMessage = "Guardian ID is invalid.")]
    public int GuardianID { get; set; }


    [Required(ErrorMessage = "Student ID is required.")]
    [Range(1, int.MaxValue, ErrorMessage = "Student ID is invalid.")]
    public int StudentID { get; set; }


    [Required(ErrorMessage = "Relationship type is required (e.g., Father, Mother, etc.).")]
    [StringLength(50, ErrorMessage = "Relationship type cannot exceed 50 characters.")]
    public string RelationshipType { get; set; } = null!;

    public virtual Guardian Guardian { get; set; } = null!;

    public virtual Student Student { get; set; } = null!;
}
