// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace  SMS.Domain.Entities;

public partial class Stage
{
    public int StageID { get; set; }

    public string StageName { get; set; } = null!;

    public virtual ICollection<GradeLevel> GradeLevels { get; set; } = new List<GradeLevel>();
}
