// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using SMS.Domain.Entities;
using System.Collections.Generic;

namespace  SMS.Domain.Entities;

public partial class Subject
{
    public int SubjectID { get; set; }

    public string SubjectName { get; set; } = null!;

    public bool IsActive { get; set; }

    public virtual ICollection<ClassSubject> ClassSubjects { get; set; } = new List<ClassSubject>();

    public virtual ICollection<StudentGrade> StudentGrades { get; set; } = new List<StudentGrade>();
}
