// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace  SMS.Core.Entities;

public partial class Track
{
    public int TrackID { get; set; }

    public string TrackName { get; set; } = null!;

    public bool IsActive { get; set; }

    public virtual ICollection<GradeLevel> GradeLevels { get; set; } = new List<GradeLevel>();
}
