// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using SMS.Core.Entities;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace SMS.DataAccess;

[DebuggerStepThrough]
public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Class> Classes { get; set; }

    public virtual DbSet<ClassSubject> ClassSubjects { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<Enrollment> Enrollments { get; set; }

    public virtual DbSet<ExamType> ExamTypes { get; set; }

    public virtual DbSet<GradeLevel> GradeLevels { get; set; }

    public virtual DbSet<Guardian> Guardians { get; set; }

    public virtual DbSet<Guardians_Student> Guardians_Students { get; set; }

    public virtual DbSet<Person> People { get; set; }

    public virtual DbSet<Stage> Stages { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<StudentGrade> StudentGrades { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    public virtual DbSet<Track> Tracks { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.ClassConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.ClassSubjectConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.CountryConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.EnrollmentConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.ExamTypeConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.GradeLevelConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.GuardianConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.Guardians_StudentConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.PersonConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.StageConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.StudentConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.StudentGradeConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.SubjectConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.TeacherConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.TrackConfiguration());

        modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
